const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.LayerVisible
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap: 0},
	{Health: 0},
	{PlayerAnim: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerBox: 0},
	{Keyboard: 0},
	{Action: 0},
	{Enemy: 0},
	{EdgeMarker: 0},
	{Sine: 0},
	{Pickup: 0},
	{txtScore: 0},
	{HealthBar: 0},
	{GameOverText: 0},
	{GameOverBackground: 0},
	{Background1: 0},
	{Background2: 0},
	{Background3: 0},
	{Overlay: 0},
	{TryAgainButton: 0},
	{Title: 0},
	{Instructions: 0},
	{StartButton: 0},
	{Background4: 0},
	{Background5: 0},
	{Background6: 0},
	{Overlay2: 0},
	{Tilemap2: 0},
	{Score: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	PlayerAnim: class extends self.ISpriteInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EdgeMarker: class extends self.ISpriteInstance {},
	Pickup: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	GameOverText: class extends self.ITextInstance {},
	GameOverBackground: class extends self.ISpriteInstance {},
	Background1: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	Background3: class extends self.ISpriteInstance {},
	Overlay: class extends self.ISpriteInstance {},
	TryAgainButton: class extends self.IButtonInstance {},
	Title: class extends self.ITextInstance {},
	Instructions: class extends self.ITextInstance {},
	StartButton: class extends self.IButtonInstance {},
	Background4: class extends self.ISpriteInstance {},
	Background5: class extends self.ISpriteInstance {},
	Background6: class extends self.ISpriteInstance {},
	Overlay2: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {}
}